### ISSUE TITLE
Tests that are run too quickly after init will fail due to "hostname error" from DB API 

### ISSUE THREAD

**Issue by westrachel** [team-aglr/edemame#15]
If a user executes "edamame run test --file ./test.js vus --200" quickly after "edamame init" finishes, they may get a "could not resolve hostname error" due to the curl post request to the db api failing. If the user gives it enough time and re-runs "edamame run test" it will eventually work. 2 possible ways to fix this that initially come to mind:

(1) in utilities/dbApi.js, in the newTestId() function, set a timeout before executing "exec(`curl -X POST ${url}/tests`)", so that the db api will be accessible to make a post request from. I don't know how much time is required before this would successfully run

(2) alter utilities/dbApi.js's newTestId() function to add error handling and repeated tries, so that this function will continue to make curl post requests to get a new test id until it can successfully make one. If this approach is taken, there should probably be a maximum number of retries set to prevent potentially infinite number of retries if the db api is down/there's some other issue causing the curl post request to fail

**Comment by lukeoguro** [comment]
I think @gcpinckert's update to the DP API will fix this but leaving this open for now for further investigation.

**Comment by lukeoguro** [comment]
See @gcpinckert's comment in #102, but I think the below error message is from a similar issue.

```
--> edamame run --file ./k6_tests/test1.js                                                                               18:54:52  羽22m 30.212s
[06:55:42:378] ℹ Reading test script...
[06:55:42:381] ✔ Successfully read test script.
[06:55:42:381] ℹ Initializing load test with 1 load generator (5000 VUs per pod)...
[06:55:43:997] ✖ Error running test: Error: getaddrinfo ENOTFOUND a90b4e77762a244709151e2cbadc4523-982894087.us-west-2.elb.amazonaws.com
```

**Comment by westrachel** [comment]
I'm still running into this issue if a test is run pretty quickly after the cluster is initialized.

Timestamps/messages:
```
[05:26:39:122] ✔ Cluster configured. Welcome to Edamame!
Rachels-Air:k6_tests rachwest$ edamame run --path test1.js    // my branch didn't have the --file change
[05:27:09:879] ℹ Reading test script...
[05:27:09:888] ✔ Successfully read test script.
[05:27:09:888] ℹ Initializing load test with 1 node...
[05:27:11:383] ✖ Error running test: Error: getaddrinfo ENOTFOUND k8s-default-ingressd-14af028797-1466942056.us-west-2.elb.amazonaws.com
Rachels-Air:k6_tests rachwest$ kubectl describe ingress     // check ingress exists/was created properly
Name:             ingress-db-api
Labels:           <none>
Namespace:        default
Address:          k8s-default-ingressd-14af028797-1466942056.us-west-2.elb.amazonaws.com
Ingress Class:    <none>
Default backend:  <default>
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           
              /   db-api-service:4444 (192.168.40.249:4444)
Annotations:  alb.ingress.kubernetes.io/inbound-cidrs: 35.XX.17.XX/32
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              kubernetes.io/ingress.class: alb
Events:
  Type    Reason                  Age                From     Message
  ----    ------                  ----               ----     -------
  Normal  SuccessfullyReconciled  78s (x2 over 79s)  ingress  Successfully reconciled
Rachels-Air:k6_tests rachwest$ kubectl get pods                 // make sure db api pod is running
NAME                      READY   STATUS    RESTARTS        AGE
db-api-6cbdd8d796-9pfm9   1/1     Running   3 (2m36s ago)   3m13s
grafana-88574fb46-jlwzj   1/1     Running   0               2m44s
psql-0                    1/1     Running   0               2m57s
Rachels-Air:k6_tests rachwest$ edamame run -p test1.js  // give db api more time to set up; no more error
[05:29:36:357] ℹ Reading test script...
[05:29:36:361] ✔ Successfully read test script.
[05:29:36:361] ℹ Initializing load test with 1 node...
[05:30:12:970] ✔ Successfully initialized load test.
[05:30:12:971] ℹ Running load test...
```

I think we could add a delayed retry of `const testId = await dbApi.newTestId(testPath, name);` in `src/commands/runTest.js` if it fails b/c dbApi isn't accessible yet.

**Comment by westrachel** [comment]
#119
