### ISSUE TITLE
Delete EBS volumes when cluster is destroyed

### ISSUE THREAD

**Issue by westrachel** [team-aglr/edemame#17]
In utilities/cluster.js, the destroy() function has a placeholder/commented out section for applying kubectl commands to delete the pv/pvcs. This section needs to be finished so that these components are removed when the cluster is deleted. Also, I'm not currently sure if we need to apply additional logic/commands to ensure the EBS is deleted too

also, does this deletion logic need to be executed anywhere else/prospectively during the init phase or runTest phase?

**Comment by lukeoguro** [comment]
I think we need to make sure the EBS volumes are deleted when the cluster is deleted. Could you look into this @gcpinckert?

**Comment by gcpinckert** [comment]
I think we just have to make sure that the [reclaim policy](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming) for associated EBS volumes is set to `Delete`. I'll look into that.

**Comment by lukeoguro** [comment]
Addressed in fc2361e
