### ISSUE TITLE
localhost grafana dashboard access

### ISSUE THREAD

**Issue by westrachel** [team-aglr/edemame#19]
In utilities/cluster.js, applyGrafanaManifests(), has the commented out kubectl function call:
.then(() => kubectl.portForward("service/grafana", GRAF_PORT, GRAF_PORT))

This is commented out, because the pod running grafana is still in the pending state, so we can't port-forward to it. Possible  solutions:

(1) add logic that will delay execution of this until the pod is confirmed as being ready and then run this portforward command
(2) move this logic to the runTest command, because hopefully by then the grafana pod will be ready and we don't have to poll/confirm status of the pod. Although, I think we'd want to port forward during the "edamame init" process, so that the user could get local access to grafana before they run the test, so that they can have grafana open/see data flow in in "real time" as the test starts.

Also, need to check that the kubectl.portForward() function is defined appropriately in that the '&' added to the end causes it to run in the background/not stall execution. If it stalls in execution, then the promise chain of "edamame init" won't end

**Comment by lukeoguro** [comment]
I'm going to merge this with #28. All points listed here are relevant.

Duplicate of #28
