### ISSUE TITLE
Investigate necessity of custom password

### ISSUE THREAD

**Issue by westrachel** [team-aglr/edemame#20]
do we want to make users confirm the password they enter for pg/grafana access?

this would involve updating utilities/userInput.js's logic

**Comment by lukeoguro** [comment]
Question for team: do we even need users to enter a password? My understanding right now is that there are two places where the password is used:

- Grafana dashboard login
- Postgres login for both `edamame` and `edamame_reader`

If access to the Grafana dashboard is secure with port-forward, then the default `admin` password can be used. The password for `edamame` shouldn't be necessary for the user, and `edamame_reader` should only be needed by the Grafana dashboard, which should be pre-configured.

**Comment by lukeoguro** [comment]
Resolved in 0fffc80
