### ISSUE TITLE
Grafana pod stuck on "ContainerCreating"

### ISSUE THREAD

**Issue by westrachel** [team-aglr/edemame#22]
the grafana configmaps/manifests were applied during the edamame init phase without an error occurring, but when I checked the status of all pods after I ran a test the grafana pod had status still showing as "ContainerCreating". I don't think it should be that slow. I think grafana_datasource.yaml has the correct database name, but the user may be incorrect? utilities/manifest.js is writing the same username to both grafana_datasource.yaml and the pg_secret.yaml, but I think "_reader" needs to be appended to grafana_datasource.yaml. I'm not sure that change alone with fix the stuck on container creating issue

**Comment by lukeoguro** [comment]
I didn't have this error this morning, but let's look into this.
