### ISSUE TITLE
statsite pg db connection issue

### ISSUE THREAD

**Issue by westrachel** [team-aglr/edemame#24]
I commented out the logic in utilities/cluster.js's phaseOutK6() function so that after executing "edmame run test --file ./test.js --vus 200" I could bin/bash into the psql pod and query from the database to make sure it's getting test data. The query to the samples table showed that it was empty after the k6 load test successfully ran, so data currently isn't being recorded into the database from statsite. The query to the tests table did return the testID value generated/written to the k6 custom resource, so the connection to the postgres database via the db api is working at least.

**Comment by lukeoguro** [comment]
Resolved in 1dd1f38
