### ISSUE TITLE
Expand `tests` table so that it includes test name

### ISSUE THREAD

**Issue by westrachel** [team-aglr/edemame#25]
this is low priority, but add back flag to "edamame run test" command to allow user to pass in a custom name to associate with their specific test/grafana dashboard, so that internally we can pass around a db generated test id as needed, but externally to user, just show them the specific test name

**Comment by lukeoguro** [comment]
I think this isn't necessary for our MVP, but we should expand the `tests` table in our next update. The users should be identifying tests by a randomly generated test name or a custom specified one, instead of IDs.

**Comment by lukeoguro** [comment]
Closing in favor of #83
