### ISSUE TITLE
Instead of mutating YAML files, create "templates" and create new YAML files as necessary

### ISSUE THREAD

**Issue by lukeoguro** [team-aglr/edemame#29]
Currently, we are mutating YAML files with necessary data for `postgres_secret` and `grafana_datasource`. We should likely create "templates" and store custom templates in a git-ignored directory.

**Comment by gcpinckert** [comment]
The first part of this issue was fixed by PR #74 . Closing this issue in favor of issue #75 , which is next steps to achieve "templates" for config files.
