### ISSUE TITLE
Show `stdout` for `exec` commands

### ISSUE THREAD

**Issue by lukeoguro** [team-aglr/edemame#49]
Currently, we don't see any helpful messages when a command files.

![Image](https://user-images.githubusercontent.com/26818975/224837798-52053535-7cf6-4f8a-80e5-8aa3a6eb70c3.png)

We need to redirect `stdout` from `exec` commands so debugging is easier.

![Image](https://user-images.githubusercontent.com/26818975/224837865-91307ca2-8261-4950-86fc-73081c1c9290.png)

**Comment by westrachel** [comment]
#116
